# Generated by Django 3.0.3 on 2020-02-16 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyladies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendee_type',
            field=models.CharField(blank=True, choices=[('o', 'Organizer'), ('f', 'First Timer'), ('r', 'Repeat Attendee')], default='f', help_text='Attendee type', max_length=1),
        ),
        migrations.CreateModel(
            name='EventInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyladies.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyladies.EventInstance'),
        ),
    ]
