# Generated by Django 3.0.3 on 2020-02-16 21:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyladies', '0002_auto_20200216_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='CheckIn',
        ),
    ]
